# Config file for automatic testing at travis-ci.org

language: python

python:
#  - "2.5"
#  - "2.6"
  - "2.7"
  - "3.2"

# command to install dependencies
install:
  - python setup.py install

# command to run tests
script:
  - cd src/ephem/tests/
  - python -m unittest discover
